create table if not exists public.global_chat_messages (
  id_chat_message bigint generated by default as identity primary key,
  id_user integer not null references public.users(id_user) on delete cascade,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists global_chat_messages_created_at_idx
  on public.global_chat_messages (created_at);

create index if not exists global_chat_messages_id_user_created_at_idx
  on public.global_chat_messages (id_user, created_at);

alter table public.global_chat_messages enable row level security;

drop policy if exists "Authenticated users can read recent global chat messages"
  on public.global_chat_messages;

create policy "Authenticated users can read recent global chat messages"
  on public.global_chat_messages
  for select
  to authenticated
  using (created_at >= now() - interval '7 days');

grant select on public.global_chat_messages to authenticated;

create or replace function public.prune_global_chat_messages()
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.global_chat_messages
  where created_at < now() - interval '7 days';
$$;

create or replace function public.prune_global_chat_messages_trigger()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.prune_global_chat_messages();
  return null;
end;
$$;

drop trigger if exists prune_global_chat_messages_before_insert
  on public.global_chat_messages;

create trigger prune_global_chat_messages_before_insert
  before insert on public.global_chat_messages
  for each statement
  execute function public.prune_global_chat_messages_trigger();

create or replace function public.list_global_chat_messages()
returns table (
  id_chat_message bigint,
  id_user integer,
  body text,
  created_at timestamptz,
  first_name text,
  last_name text,
  email text,
  profile_url text
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  perform public.prune_global_chat_messages();

  return query
    select
      m.id_chat_message,
      m.id_user,
      m.body,
      m.created_at,
      u.first_name::text,
      u.last_name::text,
      u.email::text,
      u.profile_url::text
    from public.global_chat_messages as m
    join public.users as u on u.id_user = m.id_user
    where m.created_at >= now() - interval '7 days'
      and coalesce(u.is_deleted, false) = false
      and coalesce(u.is_banned, false) = false
      and (u.suspended_until is null or u.suspended_until <= now())
    order by m.created_at asc, m.id_chat_message asc;
end;
$$;

create or replace function public.send_global_chat_message(p_body text)
returns table (
  id_chat_message bigint,
  id_user integer,
  body text,
  created_at timestamptz,
  first_name text,
  last_name text,
  email text,
  profile_url text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_body text := btrim(coalesce(p_body, ''));
  v_user_id integer;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  if char_length(v_body) = 0 then
    raise exception 'Message cannot be empty';
  end if;

  if char_length(v_body) > 500 then
    raise exception 'Message must be 500 characters or fewer';
  end if;

  select u.id_user
    into v_user_id
  from public.users as u
  where u.supabase_uid = auth.uid()::text
    and coalesce(u.is_deleted, false) = false
    and coalesce(u.is_banned, false) = false
    and (u.suspended_until is null or u.suspended_until <= now())
  limit 1;

  if v_user_id is null then
    raise exception 'User not found or unavailable';
  end if;

  perform public.prune_global_chat_messages();

  return query
    with inserted as (
      insert into public.global_chat_messages (id_user, body)
      values (v_user_id, v_body)
      returning
        global_chat_messages.id_chat_message,
        global_chat_messages.id_user,
        global_chat_messages.body,
        global_chat_messages.created_at
    )
    select
      m.id_chat_message,
      m.id_user,
      m.body,
      m.created_at,
      u.first_name::text,
      u.last_name::text,
      u.email::text,
      u.profile_url::text
    from inserted as m
    join public.users as u on u.id_user = m.id_user;
end;
$$;

revoke all on function public.prune_global_chat_messages() from public;
revoke all on function public.prune_global_chat_messages_trigger() from public;
revoke all on function public.list_global_chat_messages() from public;
revoke all on function public.send_global_chat_message(text) from public;

grant execute on function public.list_global_chat_messages() to authenticated;
grant execute on function public.send_global_chat_message(text) to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'global_chat_messages'
  ) then
    execute 'alter publication supabase_realtime add table public.global_chat_messages';
  end if;
end;
$$;
