create or replace function public.is_current_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.users as u
    where u.supabase_uid = auth.uid()::text
      and u.id_type = 2
      and coalesce(u.is_deleted, false) = false
      and coalesce(u.is_banned, false) = false
      and (u.suspended_until is null or u.suspended_until <= now())
  );
$$;

create table if not exists public.site_notifications (
  id_notification bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 120),
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  cover_url text check (cover_url is null or char_length(btrim(cover_url)) between 1 and 2048),
  created_by integer references public.users(id_user) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.site_notifications
  alter column cover_url drop not null;

create index if not exists site_notifications_active_created_at_idx
  on public.site_notifications (active, created_at desc);

create table if not exists public.user_notification_reads (
  id_notification bigint not null references public.site_notifications(id_notification) on delete cascade,
  id_user integer not null references public.users(id_user) on delete cascade,
  read_at timestamptz not null default now(),
  primary key (id_notification, id_user)
);

create index if not exists user_notification_reads_id_user_idx
  on public.user_notification_reads (id_user);

alter table public.site_notifications enable row level security;
alter table public.user_notification_reads enable row level security;

drop policy if exists "Authenticated users can read active site notifications"
  on public.site_notifications;

create policy "Authenticated users can read active site notifications"
  on public.site_notifications
  for select
  to authenticated
  using (active = true);

drop policy if exists "Admins can insert site notifications"
  on public.site_notifications;

create policy "Admins can insert site notifications"
  on public.site_notifications
  for insert
  to authenticated
  with check (public.is_current_admin());

drop policy if exists "Users can read their notification read rows"
  on public.user_notification_reads;

create policy "Users can read their notification read rows"
  on public.user_notification_reads
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.users as u
      where u.id_user = user_notification_reads.id_user
        and u.supabase_uid = auth.uid()::text
    )
  );

drop policy if exists "Users can insert their notification read rows"
  on public.user_notification_reads;

create policy "Users can insert their notification read rows"
  on public.user_notification_reads
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.users as u
      where u.id_user = user_notification_reads.id_user
        and u.supabase_uid = auth.uid()::text
    )
  );

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'notification-covers',
  'notification-covers',
  true,
  3145728,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can read notification covers"
  on storage.objects;

create policy "Public can read notification covers"
  on storage.objects
  for select
  to public
  using (bucket_id = 'notification-covers');

drop policy if exists "Admins can upload notification covers"
  on storage.objects;

create policy "Admins can upload notification covers"
  on storage.objects
  for insert
  to authenticated
  with check (
    bucket_id = 'notification-covers'
    and public.is_current_admin()
  );

create or replace function public.list_site_notifications(p_limit integer default 20)
returns table (
  id_notification bigint,
  title text,
  body text,
  cover_url text,
  created_at timestamptz,
  is_read boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer;
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 50);
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select u.id_user
    into v_user_id
  from public.users as u
  where u.supabase_uid = auth.uid()::text
    and coalesce(u.is_deleted, false) = false
    and coalesce(u.is_banned, false) = false
    and (u.suspended_until is null or u.suspended_until <= now())
  limit 1;

  if v_user_id is null then
    raise exception 'User not found or unavailable';
  end if;

  return query
    select
      n.id_notification,
      n.title,
      n.body,
      n.cover_url,
      n.created_at,
      exists (
        select 1
        from public.user_notification_reads as r
        where r.id_notification = n.id_notification
          and r.id_user = v_user_id
      ) as is_read
    from public.site_notifications as n
    where n.active = true
    order by n.created_at desc, n.id_notification desc
    limit v_limit;
end;
$$;

create or replace function public.get_unread_site_notification_count()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer;
  v_count integer;
begin
  if auth.uid() is null then
    return 0;
  end if;

  select u.id_user
    into v_user_id
  from public.users as u
  where u.supabase_uid = auth.uid()::text
    and coalesce(u.is_deleted, false) = false
    and coalesce(u.is_banned, false) = false
    and (u.suspended_until is null or u.suspended_until <= now())
  limit 1;

  if v_user_id is null then
    return 0;
  end if;

  select count(*)::integer
    into v_count
  from public.site_notifications as n
  where n.active = true
    and not exists (
      select 1
      from public.user_notification_reads as r
      where r.id_notification = n.id_notification
        and r.id_user = v_user_id
    );

  return coalesce(v_count, 0);
end;
$$;

create or replace function public.mark_site_notification_read(p_notification_id bigint)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id integer;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select u.id_user
    into v_user_id
  from public.users as u
  where u.supabase_uid = auth.uid()::text
    and coalesce(u.is_deleted, false) = false
    and coalesce(u.is_banned, false) = false
    and (u.suspended_until is null or u.suspended_until <= now())
  limit 1;

  if v_user_id is null then
    raise exception 'User not found or unavailable';
  end if;

  if not exists (
    select 1
    from public.site_notifications as n
    where n.id_notification = p_notification_id
      and n.active = true
  ) then
    raise exception 'Notification not found';
  end if;

  insert into public.user_notification_reads (id_notification, id_user)
  values (p_notification_id, v_user_id)
  on conflict (id_notification, id_user)
  do update set read_at = excluded.read_at;

  return true;
end;
$$;

create or replace function public.create_site_notification(
  p_title text,
  p_body text,
  p_cover_url text
)
returns table (
  id_notification bigint,
  title text,
  body text,
  cover_url text,
  created_at timestamptz,
  is_read boolean
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text := btrim(coalesce(p_title, ''));
  v_body text := btrim(coalesce(p_body, ''));
  v_cover_url text := nullif(btrim(coalesce(p_cover_url, '')), '');
  v_user_id integer;
begin
  if not public.is_current_admin() then
    raise exception 'Admin access required';
  end if;

  if char_length(v_title) = 0 then
    raise exception 'Title is required';
  end if;

  if char_length(v_title) > 120 then
    raise exception 'Title must be 120 characters or fewer';
  end if;

  if char_length(v_body) = 0 then
    raise exception 'Description is required';
  end if;

  if char_length(v_body) > 2000 then
    raise exception 'Description must be 2000 characters or fewer';
  end if;

  if char_length(v_cover_url) > 2048 then
    raise exception 'Cover URL is too long';
  end if;

  select u.id_user
    into v_user_id
  from public.users as u
  where u.supabase_uid = auth.uid()::text
  limit 1;

  return query
    insert into public.site_notifications (title, body, cover_url, created_by)
    values (v_title, v_body, v_cover_url, v_user_id)
    returning
      site_notifications.id_notification,
      site_notifications.title,
      site_notifications.body,
      site_notifications.cover_url,
      site_notifications.created_at,
      false as is_read;
end;
$$;

revoke all on function public.is_current_admin() from public;
revoke all on function public.list_site_notifications(integer) from public;
revoke all on function public.get_unread_site_notification_count() from public;
revoke all on function public.mark_site_notification_read(bigint) from public;
revoke all on function public.create_site_notification(text, text, text) from public;

grant execute on function public.is_current_admin() to authenticated;
grant execute on function public.list_site_notifications(integer) to authenticated;
grant execute on function public.get_unread_site_notification_count() to authenticated;
grant execute on function public.mark_site_notification_read(bigint) to authenticated;
grant execute on function public.create_site_notification(text, text, text) to authenticated;

grant select on public.site_notifications to authenticated;
grant select, insert on public.user_notification_reads to authenticated;

do $$
begin
  if exists (
    select 1
    from pg_publication
    where pubname = 'supabase_realtime'
  ) and not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'site_notifications'
  ) then
    execute 'alter publication supabase_realtime add table public.site_notifications';
  end if;
end;
$$;
